"""empty message

Revision ID: 452917946253
Revises: fdfec59b68d5
Create Date: 2018-06-09 06:16:42.896726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452917946253'
down_revision = 'fdfec59b68d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('access_token_service_id_key', 'access_token', type_='unique')
    op.drop_constraint('authorization_code_service_id_key', 'authorization_code', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('authorization_code_service_id_key', 'authorization_code', ['service_id'])
    op.create_unique_constraint('access_token_service_id_key', 'access_token', ['service_id'])
    # ### end Alembic commands ###
