"""empty message

Revision ID: 60bc81ab70e3
Revises: 2fa83f5274c9
Create Date: 2018-06-09 02:24:37.411296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bc81ab70e3'
down_revision = '2fa83f5274c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_token', sa.Column('service_id', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'access_token', ['service_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access_token', type_='unique')
    op.drop_column('access_token', 'service_id')
    # ### end Alembic commands ###
