"""empty message

Revision ID: 877ea3022f66
Revises: 0b7c1a4a2072
Create Date: 2018-05-25 17:33:48.653110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877ea3022f66'
down_revision = '0b7c1a4a2072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
