"""empty message

Revision ID: 91b3fd18dda1
Revises: df9fa13323c7
Create Date: 2018-05-03 16:41:44.675062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b3fd18dda1'
down_revision = 'df9fa13323c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
