"""empty message

Revision ID: 9412854bc4e1
Revises: 877ea3022f66
Create Date: 2018-05-25 17:36:47.077861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9412854bc4e1'
down_revision = '877ea3022f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###