"""empty message

Revision ID: fdfec59b68d5
Revises: 60bc81ab70e3
Create Date: 2018-06-09 06:06:23.023688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfec59b68d5'
down_revision = '60bc81ab70e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorization_code', sa.Column('service_id', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'authorization_code', ['service_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authorization_code', type_='unique')
    op.drop_column('authorization_code', 'service_id')
    # ### end Alembic commands ###
